### ISSUE TITLE
Can't build on Windows

### ISSUE THREAD

**Issue by MarcAstr0** [rla/node-swipl#5]
I'm trying to install via npm on Windows 7 Professional, My system has the following software and packages:

| Software     | Version |
|------------ | -------------|
| Node.js       | 8.11.1   |
| SWI-Prolog | 6.2.6     |
| windows-build-tools | 2.2.1 |

When I do an `npm install` I get the following error:

```
  libswipl.cc
  win_delay_load_hook.cc
..\src\libswipl.cc(76): error C3861: 'PL_get_compound_name_arity': identifier not found [C: \Users\macasque\Code\node-rules-test\node_modules\swipl\build\swipl.vcxproj]
..\src\libswipl.cc(166): error C2065: 'PL_NIL': undeclared identifier [C:\Users\macasque\Co de\node-rules-test\node_modules\swipl\build\swipl.vcxproj]
..\src\libswipl.cc(166): error C2131: expression did not evaluate to a constant [C:\Users\m acasque\Code\node-rules-test\node_modules\swipl\build\swipl.vcxproj]
  ..\src\libswipl.cc(166): note: failure was caused by non-constant arguments or reference
  to a non-constant symbol
  ..\src\libswipl.cc(166): note: see usage of 'PL_NIL'
..\src\libswipl.cc(168): error C2065: 'PL_LIST_PAIR': undeclared identifier [C:\Users\macas que\Code\node-rules-test\node_modules\swipl\build\swipl.vcxproj]
..\src\libswipl.cc(168): error C2131: expression did not evaluate to a constant [C:\Users\m acasque\Code\node-rules-test\node_modules\swipl\build\swipl.vcxproj]
  ..\src\libswipl.cc(168): note: failure was caused by non-constant arguments or reference
  to a non-constant symbol
  ..\src\libswipl.cc(168): note: see usage of 'PL_LIST_PAIR'
..\src\libswipl.cc(178): error C2065: 'PL_BLOB': undeclared identifier [C:\Users\macasque\C ode\node-rules-test\node_modules\swipl\build\swipl.vcxproj]
..\src\libswipl.cc(178): error C2131: expression did not evaluate to a constant [C:\Users\m acasque\Code\node-rules-test\node_modules\swipl\build\swipl.vcxproj]
  ..\src\libswipl.cc(178): note: failure was caused by non-constant arguments or reference
  to a non-constant symbol
  ..\src\libswipl.cc(178): note: see usage of 'PL_BLOB'
..\src\libswipl.cc(181): error C2065: 'PL_DICT': undeclared identifier [C:\Users\macasque\C ode\node-rules-test\node_modules\swipl\build\swipl.vcxproj]
..\src\libswipl.cc(181): error C2131: expression did not evaluate to a constant [C:\Users\m acasque\Code\node-rules-test\node_modules\swipl\build\swipl.vcxproj]
  ..\src\libswipl.cc(181): note: failure was caused by non-constant arguments or reference
  to a non-constant symbol
  ..\src\libswipl.cc(181): note: see usage of 'PL_DICT'
..\src\libswipl.cc(166): error C2051: case expression not constant [C:\Users\macasque\Code\ node-rules-test\node_modules\swipl\build\swipl.vcxproj]
..\src\libswipl.cc(168): error C2051: case expression not constant [C:\Users\macasque\Code\ node-rules-test\node_modules\swipl\build\swipl.vcxproj]
..\src\libswipl.cc(178): error C2051: case expression not constant [C:\Users\macasque\Code\ node-rules-test\node_modules\swipl\build\swipl.vcxproj]
..\src\libswipl.cc(181): error C2051: case expression not constant [C:\Users\macasque\Code\ node-rules-test\node_modules\swipl\build\swipl.vcxproj]
..\src\libswipl.cc(196): warning C4244: 'initializing': conversion from 'term_t' to 'int',
possible loss of data [C:\Users\macasque\Code\node-rules-test\node_modules\swipl\build\swip l.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)

gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\macasque\Code\node-rules-test\node_modules\swipl
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN node-rules-test@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! swipl@1.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the swipl@1.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\macasque\AppData\Roaming\npm-cache\_logs\2018-04-06T15_30_54_755Z-debug.log
```

I tried installing Visual Studio Express and its build tools via its own installer but I keep getting the same error.

**Comment by rla** [comment]
Thank you for the detailed report! Your SWI-Prolog version is too old. You need 7.x series. Make sure you also understand the limitations of the library and that you do not want to prefer https://www.npmjs.com/package/swipl-stdio

I will clarify the readme to require SWI version 7.x.

**Comment by MarcAstr0** [comment]
Indeed that was it, I upgraded my SWI-Prolog version and install worked.

Thanks @rla!

**Comment by Wei-Rong** [comment]
Sorry to post to a potentially old thread, but I am having issues installing node-swipl on my Windows 10 computer too. My node.js version is v12.13.0, and my SWI-Prolog version is v8.0.3. The error I get is shown below:

D:\Program Files\swipl\CZ3005Project>npm install swipl
D:\Program Files\parser -> D:\Program Files\node_modules\@babel\parser\bin\babel-parser.js
D:\Program Files\acorn -> D:\Program Files\node_modules\acorn\bin\acorn
D:\Program Files\atob -> D:\Program Files\node_modules\atob\bin\atob.js
D:\Program Files\esvalidate -> D:\Program Files\node_modules\esprima\bin\esvalidate.js
D:\Program Files\esparse -> D:\Program Files\node_modules\esprima\bin\esparse.js
D:\Program Files\is-ci -> D:\Program Files\node_modules\is-ci\bin.js
D:\Program Files\jsesc -> D:\Program Files\node_modules\jsesc\bin\jsesc
D:\Program Files\loose-envify -> D:\Program Files\node_modules\loose-envify\cli.js
D:\Program Files\watch -> D:\Program Files\node_modules\@cnakazawa\watch\cli.js
D:\Program Files\json5 -> D:\Program Files\node_modules\json5\lib\cli.js
D:\Program Files\mkdirp -> D:\Program Files\node_modules\mkdirp\bin\cmd.js
D:\Program Files\semver -> D:\Program Files\node_modules\semver\bin\semver
D:\Program Files\sshpk-sign -> D:\Program Files\node_modules\sshpk\bin\sshpk-sign
D:\Program Files\sshpk-conv -> D:\Program Files\node_modules\sshpk\bin\sshpk-conv
D:\Program Files\sshpk-verify -> D:\Program Files\node_modules\sshpk\bin\sshpk-verify
D:\Program Files\esgenerate -> D:\Program Files\node_modules\escodegen\bin\esgenerate.js
D:\Program Files\escodegen -> D:\Program Files\node_modules\escodegen\bin\escodegen.js
D:\Program Files\uuid -> D:\Program Files\node_modules\uuid\bin\uuid
D:\Program Files\which -> D:\Program Files\node_modules\which\bin\which
D:\Program Files\sane -> D:\Program Files\node_modules\sane\src\cli.js
D:\Program Files\jest-runtime -> D:\Program Files\node_modules\jest-runtime\bin\jest-runtime.js

> swipl@1.0.4 install D:\Program Files\node_modules\swipl
> node-gyp rebuild


D:\Program Files\node_modules\swipl>if not defined npm_config_node_gyp (node "D:\Program Files\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "D:\Program Files\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Traceback (most recent call last):
  File "D:\Program Files\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 50, in <module>
    sys.exit(gyp.script_main())
  File "D:\Program Files\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 554, in script_main
    return main(sys.argv[1:])
  File "D:\Program Files\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 547, in main
    return gyp_main(args)
  File "D:\Program Files\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 523, in gyp_main
    options.duplicate_basename_check)
  File "D:\Program Files\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 139, in Load
    params['parallel'], params['root_targets'])
  File "D:\Program Files\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 2779, in Load
    variables, includes, depth, check, True)
  File "D:\Program Files\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 417, in LoadTargetBuildFile
    build_file_data, PHASE_EARLY, variables, build_file_path)
  File "D:\Program Files\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 1218, in ProcessVariablesAndConditionsInDict
    variables, build_file, 'variables')
  File "D:\Program Files\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 1225, in ProcessVariablesAndConditionsInDict
    expanded = ExpandVariables(value, phase, variables, build_file)
  File "D:\Program Files\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 914, in ExpandVariables
    sys.stderr.write(p_stderr)
TypeError: write() argument must be str, not bytes while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (D:\Program Files\node_modules\npm\node_modules\node-gyp\lib\configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "D:\\Program Files\\node.exe" "D:\\Program Files\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Program Files\node_modules\swipl
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! swipl@1.0.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the swipl@1.0.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\USER\AppData\Roaming\npm-cache\_logs\2019-11-03T16_19_30_385Z-debug.log
