### ISSUE TITLE
Usage example with facts and rules

### ISSUE THREAD

**Issue by zavalyshyn** [rla/node-swipl#9]
Hi,

I've checked your package with the simple queries you've posed at the READE.md file. 

I now wonder how can I use this package with some knowledge base of facts and rules. I mean if I have a set of facts and rules in my Prolog program, like:

```prolog
% fruit/1
fruit(apple). fruit(pear). fruit(banana).

% fruits_in/2
fruits_in(Xs, X) :- member(X, Xs), fruit(X).
```

And then I want to query this program with a query like:

``` prolog
fruits_in([carrot, apple, banana, broccoli], X).
```

How do I do that? Issuing a query is described in readme file, but saving the knowledge base is not. 

Could you please explain?

Thanks

**Comment by rla** [comment]
Hey @zavalyshyn. Saving and loading the database can be done using SWI-Prolog built-in methods. There are multiple ways of doing it as described on https://www.swi-prolog.org/pldoc/man?section=db Loading a Prolog program is done as usually, for example, by running query `consult('myprogram.pl')`.
